CREATE TABLE "POSITION" (
  POS_ID SERIAL PRIMARY KEY NOT NULL,
  POS_NAME VARCHAR(50) NOT NULL UNIQUE
  );

CREATE TABLE EMPLOYEE (
  EMP_ID SERIAL PRIMARY KEY NOT NULL,
  EMP_NAME VARCHAR(50) NOT NULL,
  dob DATE NOT NULL,
  PHONE VARCHAR (15) NOT NULL UNIQUE,
  SALARY REAl NOT NULL,
  POS_ID INTEGER REFERENCES "POSITION" (POS_ID)
  );

CREATE TABLE INGREDIENT (
  ING_ID SERIAL PRIMARY KEY NOT NULL,
  ING_NAME VARCHAR(50) NOT NULL UNIQUE,
  UNIT VARCHAR(10) NOT NULL
  );

CREATE TABLE DISH (
  D_ID SERIAL PRIMARY KEY NOT NULL,
  DISH_NAME VARCHAR(50) NOT NULL UNIQUE,
  CATEGORY VARCHAR (50) NOT NULL,
  PRICE REAL NOT NULL,
  WEIGHT REAL NOT NULL
  );

CREATE TABLE DISH_INGREDIENT (
  D_ID INTEGER REFERENCES DISH (D_ID),
  ING_ID INTEGER REFERENCES INGREDIENT (ING_ID),
  QUANTITY REAL NOT NULL,
  PRIMARY KEY (D_ID, ING_ID)
  );

CREATE TABLE "ORDER" (
  ORD_ID SERIAL PRIMARY KEY NOT NULL,
  IS_OPENED BOOLEAN NOT NULL,
  OPEN_DATE TIMESTAMP NOT NULL,
  CLOSE_DATE TIMESTAMP,
  TABLE_NUMBER INTEGER NOT NULL,
  WAITER_ID INTEGER REFERENCES EMPLOYEE (EMP_ID)
  );

  CREATE TABLE ORDER_DISH (
  ORD_ID INTEGER REFERENCES "ORDER" (ORD_ID),
  D_ID INTEGER REFERENCES DISH (D_ID),
  QUANTITY INTEGER NOT NULL,
  PRIMARY KEY (ORD_ID, D_ID)
  );

CREATE TABLE MENU (
  M_ID SERIAL PRIMARY KEY NOT NULL,
  MENU_NAME VARCHAR(50) NOT NULL UNIQUE
  );

CREATE TABLE MENU_DISH (
  M_ID INTEGER REFERENCES MENU (M_ID),
  D_ID INTEGER REFERENCES DISH (D_ID),
  PRIMARY KEY (M_ID, D_ID)
  );

CREATE TABLE STORE_HOUSE (
  ING_ID INTEGER PRIMARY KEY REFERENCES INGREDIENT (ING_ID),
  QUANTITY REAL NOT NULL
  );

CREATE TABLE PREPARED_DISH (
  PD_ID SERIAL PRIMARY KEY NOT NULL,
  WHEN_PREPARED TIMESTAMP NOT NULL,
  D_ID INTEGER REFERENCES DISH (D_ID),
  CHEF_ID INTEGER REFERENCES EMPLOYEE (EMP_ID),
  ORD_ID INTEGER REFERENCES "ORDER" (ORD_ID)
  );